<a href="https://colab.research.google.com/github/praveen1608/Praveen-Reddy_INFO5731_Spring2024/blob/main/Kadasani_PraveenReddy_Exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Students are expected to complete the exercise during lecture period to meet the active participation criteria of the course.
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of the day tomorrow, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**


## Question 1 (10 Points)
Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [1]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Classifing the sentiment analysis on customer reviews of a product.

features used-

(1)Bag-of-Words (BoW):
BoW represents each document as a vector where every element is corresponding to the frequency of the word in that document.
The Presence and frequency of the words can be captured by using this feature.

(2)TF-IDF (Term Frequency-Inverse Document Frequency):
This feature is much similar to BoW, but it calculates the importance of words by how many times they are repeating  in the entire corpus.
This feature helps in calculating the uniqueness of the words in the document.

(3)Word Embeddings:
It represents words as dense vectors in a continuous vector space. This helps is capturing the semantic relationships between the words
which is used in understanding the meaning of the text.

(4)N-grams:
This feature instead of considering single words, it considers a sequence of words. Which helps in understanding the phrases and expressions
by capturing the contextual information.

(5)Part-of-Speech(POS):
POS tags represents grammar category of words in a sentence. They capture syntsctic information, revelant to sentiment analysis.

'''

'\nClassifing the sentiment analysis on customer reviews of a product.\n\nfeatures used-\n\n(1)Bag-of-Words (BoW):\nBoW represents each document as a vector where every element is corresponding to the frequency of the word in that document.\nThe Presence and frequency of the words can be captured by using this feature.\n\n(2)TF-IDF (Term Frequency-Inverse Document Frequency):\nThis feature is much similar to BoW, but it calculates the importance of words by how many times they are repeating  in the entire corpus.\nThis feature helps in calculating the uniqueness of the words in the document.\n\n(3)Word Embeddings:\nIt represents words as dense vectors in a continuous vector space. This helps is capturing the semantic relationships between the words\nwhich is used in understanding the meaning of the text.\n\n(4)N-grams:\nThis feature instead of considering single words, it considers a sequence of words. Which helps in understanding the phrases and expressions \nby capturing the contextu

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [2]:
# You code here (Please add comments in the code):

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.util import ngrams
from nltk import pos_tag, word_tokenize
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Sample text data
texts = [
    "The product quality is consistently outstanding, exceeding my expectations every time.",
    "This product is amazing! I love it.",
    "Pricing is fair and transparent definitely value for money.",
    "The quality of this product is poor. I'm disappointed.",
    "I'm not sure about this product. It seems okay.",
]

# Bag-of-Words (BoW)
vectorizer_bow = CountVectorizer()
X_bow = vectorizer_bow.fit_transform(texts)
print("\nBag-of-Words (BoW) features:")
print(vectorizer_bow.get_feature_names_out())
print(X_bow.toarray())

# TF-IDF
vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(texts)
print("\nTF-IDF features:")
print(vectorizer_tfidf.get_feature_names_out())
print(X_tfidf.toarray())

# N-grams
ngram_range = (1, 2)  # Considering unigrams and bigrams
X_ngrams = []
for text in texts:
    tokens = word_tokenize(text)
    ngrams_list = [' '.join(gram) for gram in ngrams(tokens, n=2)]
    X_ngrams.append(ngrams_list)
print("\nN-grams features:")
print(X_ngrams)

# Part-of-Speech (POS) features
X_pos = []
for text in texts:
    tokens = word_tokenize(text)
    pos_tags = [tag for word, tag in pos_tag(tokens)]
    X_pos.append(pos_tags)
print("\nPart-of-Speech (POS) features:")
print(X_pos)

# Word Embeddings (For demonstration purposes, let's assume we have pre-trained word embeddings)
word_embeddings = {
    "amazing": [0.8, 0.2, -0.4],
    "love": [0.6, 0.1, 0.5],
    "poor": [-0.7, -0.5, 0.3],
    "disappointed": [-0.9, -0.8, 0.2],
    "okay": [0.2, 0.3, -0.6],
    "product": [0.4, -0.3, 0.7],
}
X_embeddings = []
for text in texts:
    tokens = word_tokenize(text)
    embeddings = [word_embeddings[token] for token in tokens if token in word_embeddings]
    X_embeddings.append(embeddings)
print("\nWord Embeddings features:")
print(X_embeddings)



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!



Bag-of-Words (BoW) features:
['about' 'amazing' 'and' 'consistently' 'definitely' 'disappointed'
 'every' 'exceeding' 'expectations' 'fair' 'for' 'is' 'it' 'love' 'money'
 'my' 'not' 'of' 'okay' 'outstanding' 'poor' 'pricing' 'product' 'quality'
 'seems' 'sure' 'the' 'this' 'time' 'transparent' 'value']
[[0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 0]]

TF-IDF features:
['about' 'amazing' 'and' 'consistently' 'definitely' 'disappointed'
 'every' 'exceeding' 'expectations' 'fair' 'for' 'is' 'it' 'love' 'money'
 'my' 'not' 'of' 'okay' 'outstanding' 'poor' 'pricing' 'product' 'quality'
 'seems' 'sure' 'the' 'this' 'time' 'transparent' 'value']
[[0.         0.         0.         0.33451305 0.         0.
  0.33451305 0

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [3]:
# You code here (Please add comments in the code):

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Sample text data
texts = [
    "The product quality is consistently outstanding, exceeding my expectations every time.",
    "This product is amazing! I love it.",
    "Pricing is fair and transparent definitely value for money.",
    "The quality of this product is poor. I'm disappointed.",
    "I'm not sure about this product. It seems okay.",
]

# Labels
labels = [1, 1, 1, 0, 0]  # 1 for positive, 0 for negative

# Feature extraction using TF-IDF
tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(texts)

# Feature selection using RFE (using "Wrapper" feature selection model from the paper mentioned above)
logreg = LogisticRegression()
rfe = RFE(estimator=logreg, n_features_to_select=2)
rfe.fit(X, labels)

# Ranking features based on their importance
feature_ranks = sorted(zip(tfidf_vectorizer.get_feature_names_out(), rfe.ranking_), key=lambda x: x[1], reverse=True)

# Create a DataFrame
df = pd.DataFrame(feature_ranks, columns=['Feature', 'Rank'])
print(df)


         Feature  Rank
0             it    30
1        product    29
2            the    28
3        quality    27
4             is    26
5           time    25
6          money    24
7   consistently    23
8          value    22
9    outstanding    21
10   transparent    20
11            my    19
12           for    18
13  expectations    17
14       pricing    16
15         every    15
16           and    14
17     exceeding    13
18    definitely    12
19          fair    11
20       amazing    10
21          this     9
22          love     8
23         about     7
24           not     6
25          okay     5
26         seems     4
27  disappointed     3
28          sure     2
29            of     1
30          poor     1


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [4]:
!pip install sentence-transformers


In [7]:
# You code here (Please add comments in the code):


from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Sample query and texts
query = "I loved the product, it was fantastic!"

# Converting the query and texts to BERT embeddings
model = SentenceTransformer('distilbert-base-nli-mean-tokens')
query_embedding = model.encode(query)
text_embeddings = model.encode(texts)

# Calculate cosine similarity
similarities = cosine_similarity(query_embedding.reshape(1, -1), text_embeddings)

# Rank texts based on similarity
ranked_texts = sorted(zip(similarities[0], texts), reverse=True)

print("\n")
# Create a DataFrame
df = pd.DataFrame(ranked_texts, columns=['Similarity', 'Text'])
print(df)





   Similarity                                               Text
0    0.979436                This product is amazing! I love it.
1    0.706400  The product quality is consistently outstandin...
2    0.663080  Pricing is fair and transparent definitely val...
3    0.539053    I'm not sure about this product. It seems okay.
4    0.290109  The quality of this product is poor. I'm disap...


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [6]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
In class I was not sure about these features during the explanation, but after doing this assignment, it feels like I'm confident about feature extraction now.
All the features that I worked on were so good in sentiment analysis, we were able to how many reviwes were positive and how many are negative.
By that we can say the product is worth buying.

I didn't faced any issues in this assignement, the questions were straight forward and answerable.

This exercise is related to NLP in several ways. Feature extraction, Text classification, Semantic analysis all these were helpful in real world situations
to improve business. All these work will be done using the text data which need to be collected by data professionals, analysed using ML models and to give insights.
Which means it is directly related to feild of study data science.


'''

"\nIn class I was not sure about these features during the explanation, but after doing this assignment, it feels like I'm confident about feature extraction now.\nAll the features that I worked on were so good in sentiment analysis, we were able to how many reviwes were positive and how many are negative.\nBy that we can say the product is worth buying.\n\nI didn't faced any issues in this assignement, the questions were straight forward and answerable.\n\nThis exercise is related to NLP in several ways. Feature extraction, Text classification, Semantic analysis all these were helpful in real world situations\nto improve business. All these work will be done using the text data which need to be collected by data professionals, analysed using ML models and to give insights.\nWhich means it is directly related to feild of study data science. \n\n\n"